/**
 * Local Supabase-compatible API server backed by DuckDB.
 * Mimics the Supabase REST and Auth APIs so the frontend works unchanged.
 * Swap VITE_SUPABASE_URL back to the real Supabase URL to migrate.
 */

'use strict'

const express = require('express')
const cors = require('cors')
const { DuckDBInstance } = require('@duckdb/node-api')
const jwt = require('jsonwebtoken')
const { v4: uuidv4 } = require('uuid')
const crypto = require('crypto')
const { LeadIntakeAgent } = require('./agents/lead-intake-agent')
const fs = require('fs')
const path = require('path')
const assignmentAgent = require('./agents/assignmentAgent')
const assignmentAgentGraph = require('./agents/assignmentAgentGraph')

const JWT_SECRET = 'local-dev-secret'
const PORT = 54321
const DEMO_PASSWORD = 'Passw0rd!23'

const ABC_TENANT_ID = '11111111-1111-1111-1111-111111111111'
const XYZ_TENANT_ID = '22222222-2222-2222-2222-222222222222'
const LOC_VEL_ID    = 'aaaaaaaa-0000-0000-0000-000000000001'

// Point the web app at this server with zero manual setup. .env.local is
// gitignored, so a fresh clone won't have it — we write it here on boot.
function ensureWebEnv() {
  const envPath = path.resolve(__dirname, '../web/.env.local')
  if (fs.existsSync(envPath)) return
  const body = [
    '# Auto-generated by apps/local-api — points the web app at the local DuckDB server.',
    '# Delete this file (or change the values) to use a real Supabase project instead.',
    `VITE_SUPABASE_URL=http://localhost:${PORT}`,
    'VITE_SUPABASE_ANON_KEY=local-dev-anon-key',
    '',
  ].join('\n')
  fs.writeFileSync(envPath, body)
  console.log('📝 Wrote apps/web/.env.local (pointing at the local DuckDB server)')
}

// ─── DuckDB ───────────────────────────────────────────────────────────────────

let conn
let intakeAgent
let sseCounter = 0
const sseClients = new Map()

// In-memory intake log — newest first, capped at 200 entries.
const intakeLogs = []
function pushLog(entry) {
  intakeLogs.unshift({ ...entry, timestamp: new Date().toISOString() })
  if (intakeLogs.length > 200) intakeLogs.length = 200
}

function broadcastIntakeEvent(payload) {
  const data = JSON.stringify(payload)
  for (const res of sseClients.values()) {
    try { res.write(`data: ${data}\n\n`) } catch {}
  }
}

async function initDuckDB() {
  // DUCKDB_PATH env var → file-backed DB (survives container restart in dev Docker).
  // Unset (default) → in-memory, same behaviour as before.
  const dbPath = process.env.DUCKDB_PATH || ':memory:'
  const instance = await DuckDBInstance.create(dbPath)
  conn = await instance.connect()
}

function esc(val) {
  if (val === null || val === undefined) return 'NULL'
  if (typeof val === 'number') return isNaN(val) ? 'NULL' : String(val)
  if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE'
  return `'${String(val).replace(/'/g, "''")}'`
}

function interpolate(sql, params) {
  if (!params || params.length === 0) return sql
  let i = 0
  return sql.replace(/\?/g, () => esc(params[i++]))
}

async function run(sql, params = []) {
  await conn.run(interpolate(sql, params))
}

async function all(sql, params = []) {
  const reader = await conn.runAndReadAll(interpolate(sql, params))
  return reader.getRowObjectsJson()
}

function parseJson(val) {
  if (typeof val !== 'string') return val
  const t = val.trim()
  if ((t.startsWith('{') || t.startsWith('[')) ) {
    try { return JSON.parse(t) } catch {}
  }
  return val
}

function transformRow(row) {
  const out = {}
  for (const [k, v] of Object.entries(row)) {
    out[k] = parseJson(v)
  }
  return out
}

// Mirror of parseJson, for the write path: object/array values (e.g. a jsonb
// column sent as a real JSON body value, not a pre-stringified string) must
// be stringified before binding — otherwise the DuckDB driver coerces them
// with a plain toString(), storing the literal text "[object Object]".
function serializeJson(val) {
  if (val !== null && typeof val === 'object') return JSON.stringify(val)
  return val
}

function stringifyRow(row) {
  const out = {}
  for (const [k, v] of Object.entries(row)) {
    out[k] = serializeJson(v)
  }
  return out
}

// ─── Schema ───────────────────────────────────────────────────────────────────

async function initSchema() {
  await run(`CREATE TABLE tenants (
    id VARCHAR PRIMARY KEY, name VARCHAR, brand VARCHAR,
    subscription_plan VARCHAR DEFAULT 'starter', status VARCHAR DEFAULT 'active',
    branding VARCHAR DEFAULT '{}'
  )`)
  await run(`CREATE TABLE locations (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, name VARCHAR, status VARCHAR DEFAULT 'active'
  )`)
  await run(`CREATE TABLE users (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, email VARCHAR UNIQUE,
    full_name VARCHAR, role VARCHAR, password_hash VARCHAR, created_at VARCHAR
  )`)
  await run(`CREATE TABLE customers (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, location_id VARCHAR,
    full_name VARCHAR, phone VARCHAR, email VARCHAR, city VARCHAR,
    preferred_vehicle VARCHAR, source_channel VARCHAR, created_at VARCHAR
  )`)
  await run(`CREATE TABLE leads (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, location_id VARCHAR,
    customer_id VARCHAR, source VARCHAR, stage VARCHAR DEFAULT 'new',
    score VARCHAR DEFAULT 'warm', score_value INTEGER DEFAULT 50,
    assigned_to VARCHAR, vehicle_interest VARCHAR, budget DOUBLE,
    -- Amirtha (validator agent — categorical form fields):
    budget_range VARCHAR, test_drive_requested BOOLEAN,
    purchase_timeframe VARCHAR, preferred_call_time VARCHAR, preferred_channel VARCHAR,
    enquiry_count INTEGER DEFAULT 1,
    -- Partha (intake pipeline — numeric form fields):
    test_drive_required BOOLEAN DEFAULT FALSE,
    purchase_timeline_days INTEGER,
    callback_within_days INTEGER,
    contact_medium VARCHAR,
    -- Enquiry-form signal fields (feed scoring; surfaced in lead detail Key facts):
    financing VARCHAR, nissan_relationship VARCHAR,
    brand_consideration VARCHAR, comparing_brands VARCHAR, purchase_reason VARCHAR,
    -- Csriram (scoring agent attribution — how this lead's score was produced):
    scored_by VARCHAR,
    score_reasons VARCHAR DEFAULT '[]',
    score_notice VARCHAR,
    notes VARCHAR,
    created_at VARCHAR, updated_at VARCHAR, last_activity_at VARCHAR
  )`)
  await run(`CREATE TABLE lead_events (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR,
    type VARCHAR, summary VARCHAR, metadata VARCHAR DEFAULT '{}',
    created_by VARCHAR, created_at VARCHAR
  )`)
  // Validation Agent (Phase 1) — one row per detected repeat enquiry.
  await run(`CREATE TABLE lead_interactions (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR, customer_id VARCHAR,
    interaction_type VARCHAR DEFAULT 'duplicate_enquiry', source VARCHAR,
    summary VARCHAR, metadata VARCHAR DEFAULT '{}', created_at VARCHAR
  )`)
  // Validation Agent (Phase 1) — one row per validation attempt, pass or fail.
  // lead_id is nullable: a hard-rejected lead never gets a leads row.
  await run(`CREATE TABLE validation_logs (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR,
    phone VARCHAR, email VARCHAR, status VARCHAR,
    errors VARCHAR DEFAULT '[]', warnings VARCHAR DEFAULT '[]',
    source VARCHAR, created_at VARCHAR
  )`)
  // Lead Board UI (Phase 2) — Messages/Tasks/Documents detail-view sections.
  // Call History needs no table — it's a filtered view of lead_events.
  await run(`CREATE TABLE lead_messages (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR,
    channel VARCHAR, direction VARCHAR DEFAULT 'outbound', body VARCHAR,
    source VARCHAR DEFAULT 'manual', created_by VARCHAR, created_at VARCHAR,
    -- WhatsApp Agent (Phase 4) — nullable, no existing rows break
    whatsapp_message_id VARCHAR UNIQUE, status VARCHAR,
    template_id VARCHAR, attachment_id VARCHAR, error_reason VARCHAR
  )`)
  await run(`CREATE TABLE lead_tasks (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR,
    title VARCHAR, due_at VARCHAR, status VARCHAR DEFAULT 'open',
    assigned_to VARCHAR, created_by VARCHAR, created_at VARCHAR, completed_at VARCHAR
  )`)
  // Stub only — no upload/storage wiring in this phase (see migration 0018).
  await run(`CREATE TABLE lead_documents (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR,
    file_name VARCHAR, url VARCHAR, uploaded_by VARCHAR, created_at VARCHAR
  )`)
  // WhatsApp Agent (Phase 4) — message templates, media library, delivery audit.
  await run(`CREATE TABLE message_templates (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, name VARCHAR,
    category VARCHAR, language VARCHAR DEFAULT 'en', content VARCHAR,
    variables VARCHAR DEFAULT '[]', meta_status VARCHAR DEFAULT 'pending',
    created_at VARCHAR
  )`)
  await run(`CREATE TABLE attachments (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, name VARCHAR,
    type VARCHAR, meta_media_id VARCHAR, url VARCHAR,
    size_bytes INTEGER, created_at VARCHAR
  )`)
  await run(`CREATE TABLE message_delivery_logs (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, message_id VARCHAR,
    status VARCHAR, meta_timestamp VARCHAR, webhook_payload VARCHAR DEFAULT '{}',
    created_at VARCHAR
  )`)
  // Call Intelligence Agent (Phase 5) — recordings + transcript + sentiment + analysis.
  await run(`CREATE TABLE call_recordings (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR, uploaded_by VARCHAR,
    file_name VARCHAR, recording_url VARCHAR, duration_seconds INTEGER,
    status VARCHAR DEFAULT 'uploaded', error_reason VARCHAR, created_at VARCHAR
  )`)
  await run(`CREATE TABLE call_transcripts (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, call_id VARCHAR,
    transcript VARCHAR, language_detected VARCHAR, created_at VARCHAR
  )`)
  await run(`CREATE TABLE call_sentiment (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, call_id VARCHAR,
    sentiment VARCHAR, confidence DOUBLE, created_at VARCHAR
  )`)
  await run(`CREATE TABLE call_analysis (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, call_id VARCHAR UNIQUE,
    customer_summary VARCHAR DEFAULT '[]', interest_level VARCHAR, buying_intent_score INTEGER,
    competitors VARCHAR DEFAULT '[]', competitor_risk VARCHAR, price_sensitivity VARCHAR,
    purchase_timeline VARCHAR, test_drive_interest BOOLEAN, followup_requested BOOLEAN,
    recommended_action VARCHAR, reasoning VARCHAR DEFAULT '[]', raw_analysis VARCHAR,
    created_at VARCHAR
  )`)
  // Workflow Agent (Phase 3) — one row per automatic next-action decision.
  await run(`CREATE TABLE workflow_actions (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR,
    classification VARCHAR, actions VARCHAR DEFAULT '[]', reasoning VARCHAR,
    rule_matched VARCHAR, trigger_source VARCHAR,
    escalated BOOLEAN DEFAULT FALSE, created_at VARCHAR
  )`)
  // Dynamic Re-Scoring (Phase 6) — append-only score change history.
  await run(`CREATE TABLE lead_score_history (
    id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid()::VARCHAR,
    tenant_id VARCHAR NOT NULL, lead_id VARCHAR NOT NULL,
    score VARCHAR NOT NULL, score_value INTEGER DEFAULT 0,
    previous_score VARCHAR, previous_value INTEGER,
    trigger VARCHAR NOT NULL, scored_by VARCHAR,
    score_reasons VARCHAR DEFAULT '[]', created_at VARCHAR
  )`)
  // Dynamic Re-Scoring (Phase 6) — raw trigger event log.
  await run(`CREATE TABLE score_events (
    id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid()::VARCHAR,
    tenant_id VARCHAR NOT NULL, lead_id VARCHAR NOT NULL,
    event_type VARCHAR NOT NULL, metadata VARCHAR DEFAULT '{}',
    processed BOOLEAN DEFAULT FALSE, created_at VARCHAR
  )`)
  // Event-Driven Architecture (Phase 7) — persisted event-bus log.
  await run(`CREATE TABLE domain_events (
    id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid()::VARCHAR,
    tenant_id VARCHAR NOT NULL, lead_id VARCHAR,
    event_type VARCHAR NOT NULL, payload VARCHAR DEFAULT '{}',
    source VARCHAR DEFAULT 'system', status VARCHAR DEFAULT 'pending',
    attempts INTEGER DEFAULT 0, error VARCHAR,
    created_at VARCHAR, processed_at VARCHAR
  )`)
  await run(`CREATE TABLE notifications (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, title VARCHAR,
    message VARCHAR, status VARCHAR DEFAULT 'unread', created_at VARCHAR
  )`)
  await run(`CREATE TABLE audit_logs (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, action VARCHAR,
    entity_type VARCHAR, entity_id VARCHAR,
    metadata VARCHAR DEFAULT '{}', created_at VARCHAR
  )`)
  await run(`CREATE TABLE campaigns (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, location_id VARCHAR,
    name VARCHAR, theme VARCHAR, objective VARCHAR, status VARCHAR DEFAULT 'draft',
    channels VARCHAR DEFAULT '[]', start_date VARCHAR, end_date VARCHAR,
    budget DOUBLE, created_at VARCHAR, updated_at VARCHAR
  )`)
  await run(`CREATE TABLE campaign_posts (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, campaign_id VARCHAR,
    title VARCHAR, caption VARCHAR, cta VARCHAR, hashtags VARCHAR DEFAULT '[]',
    channel VARCHAR, status VARCHAR DEFAULT 'draft', compliance VARCHAR DEFAULT 'unchecked',
    vehicle VARCHAR, offer VARCHAR, poster_url VARCHAR, poster_prompt VARCHAR,
    scheduled_at VARCHAR, published_at VARCHAR, created_at VARCHAR, updated_at VARCHAR
  )`)
  await run(`CREATE TABLE campaign_insights (
    id VARCHAR PRIMARY KEY, campaign_id VARCHAR, reach INTEGER DEFAULT 0,
    impressions INTEGER DEFAULT 0, engagement INTEGER DEFAULT 0,
    leads_generated INTEGER DEFAULT 0, conversions INTEGER DEFAULT 0,
    spend DOUBLE DEFAULT 0, cost_per_lead DOUBLE DEFAULT 0,
    conversion_rate DOUBLE DEFAULT 0, captured_at VARCHAR
  )`)
  await run(`CREATE TABLE market_signals (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, kind VARCHAR, title VARCHAR,
    detail VARCHAR, metric_label VARCHAR, metric_value VARCHAR,
    severity VARCHAR DEFAULT 'low', source_module VARCHAR,
    status VARCHAR DEFAULT 'open', created_at VARCHAR
  )`)
  await run(`CREATE TABLE copilot_conversations (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, user_id VARCHAR,
    title VARCHAR, created_at VARCHAR, updated_at VARCHAR
  )`)
  await run(`CREATE TABLE copilot_messages (
    id VARCHAR PRIMARY KEY, conversation_id VARCHAR, tenant_id VARCHAR,
    role VARCHAR, content VARCHAR, citations VARCHAR DEFAULT '[]', created_at VARCHAR
  )`)
  await run(`CREATE TABLE sales_executives (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR, name VARCHAR, status VARCHAR DEFAULT 'active',
    current_lead_count INTEGER DEFAULT 0, max_lead_limit INTEGER DEFAULT 10
  )`)
  await run(`CREATE TABLE lead_assignments (
    assignment_id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR, executive_id VARCHAR,
    score VARCHAR, priority_rank INTEGER DEFAULT 1, assigned_at VARCHAR DEFAULT CURRENT_TIMESTAMP
  )`)
  await run(`CREATE TABLE lead_completions (
    completion_id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR, executive_id VARCHAR,
    completed_at VARCHAR DEFAULT CURRENT_TIMESTAMP
  )`)
  await run(`CREATE TABLE assignment_notifications (
    notification_id VARCHAR PRIMARY KEY, tenant_id VARCHAR, lead_id VARCHAR,
    executive_id VARCHAR, event_type VARCHAR, message VARCHAR,
    is_read BOOLEAN DEFAULT FALSE, created_at VARCHAR
  )`)
  // Context Planner (Phase 1 of the Context/SEO/AEO vertical, docs/planner/).
  await run(`CREATE TABLE context_plans (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR NOT NULL,
    input_type VARCHAR NOT NULL, url VARCHAR, normalized_url VARCHAR,
    company_name VARCHAR, website VARCHAR, region VARCHAR, industry VARCHAR,
    products VARCHAR, services VARCHAR, description VARCHAR,
    status VARCHAR DEFAULT 'pending', errors VARCHAR DEFAULT '[]',
    created_at VARCHAR, updated_at VARCHAR
  )`)
  // Website Extraction Engine (Phase 2 of the Context/SEO/AEO vertical, docs/planner/).
  await run(`CREATE TABLE website_extractions (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR NOT NULL, context_id VARCHAR NOT NULL,
    url VARCHAR, status VARCHAR DEFAULT 'queued',
    extraction_data VARCHAR, errors VARCHAR DEFAULT '[]',
    created_at VARCHAR, updated_at VARCHAR, started_at VARCHAR, completed_at VARCHAR
  )`)
  // Company Summary (Phase 3 of the Context/SEO/AEO vertical, docs/planner/).
  await run(`CREATE TABLE company_summaries (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR NOT NULL, extraction_id VARCHAR NOT NULL, context_id VARCHAR NOT NULL,
    company_name VARCHAR, website VARCHAR, region VARCHAR, industry VARCHAR,
    products VARCHAR DEFAULT '[]', services VARCHAR DEFAULT '[]',
    description VARCHAR, verdict VARCHAR,
    status VARCHAR DEFAULT 'pending', errors VARCHAR DEFAULT '[]',
    created_at VARCHAR, updated_at VARCHAR
  )`)
  // SEO Agent (Phase 4 of the Context/SEO/AEO vertical, docs/planner/).
  await run(`CREATE TABLE seo_analyses (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR NOT NULL, extraction_id VARCHAR NOT NULL, context_id VARCHAR NOT NULL,
    status VARCHAR DEFAULT 'queued', analysis_data VARCHAR, overall_score INTEGER, errors VARCHAR DEFAULT '[]',
    created_at VARCHAR, updated_at VARCHAR, started_at VARCHAR, completed_at VARCHAR
  )`)
  // AEO Agent (Phase 5 of the Context/SEO/AEO vertical, docs/planner/).
  await run(`CREATE TABLE aeo_analyses (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR NOT NULL, extraction_id VARCHAR NOT NULL, context_id VARCHAR NOT NULL,
    status VARCHAR DEFAULT 'queued', analysis_data VARCHAR, overall_score INTEGER, errors VARCHAR DEFAULT '[]',
    created_at VARCHAR, updated_at VARCHAR, started_at VARCHAR, completed_at VARCHAR
  )`)
  // Recommendation Engine (Phase 6 of the Context/SEO/AEO vertical, docs/planner/).
  await run(`CREATE TABLE recommendation_reports (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR NOT NULL, extraction_id VARCHAR NOT NULL,
    context_id VARCHAR NOT NULL, seo_analysis_id VARCHAR NOT NULL, aeo_analysis_id VARCHAR NOT NULL,
    status VARCHAR DEFAULT 'queued', report_data VARCHAR, combined_score INTEGER, errors VARCHAR DEFAULT '[]',
    created_at VARCHAR, updated_at VARCHAR, started_at VARCHAR, completed_at VARCHAR
  )`)
  // Report Generator (Phase 7 of the Context/SEO/AEO vertical, docs/planner/).
  await run(`CREATE TABLE generated_reports (
    id VARCHAR PRIMARY KEY, tenant_id VARCHAR NOT NULL, extraction_id VARCHAR NOT NULL,
    context_id VARCHAR NOT NULL, recommendation_report_id VARCHAR NOT NULL,
    seo_analysis_id VARCHAR NOT NULL, aeo_analysis_id VARCHAR NOT NULL, company_summary_id VARCHAR,
    status VARCHAR DEFAULT 'queued', report_data VARCHAR, markdown_content VARCHAR, overall_score INTEGER,
    errors VARCHAR DEFAULT '[]', created_at VARCHAR, updated_at VARCHAR, started_at VARCHAR, completed_at VARCHAR
  )`)
}

// ─── Seed ─────────────────────────────────────────────────────────────────────

async function seed() {
  const ABC = '11111111-1111-1111-1111-111111111111'
  const XYZ = '22222222-2222-2222-2222-222222222222'
  const LOC_VEL = 'aaaaaaaa-0000-0000-0000-000000000001'
  const LOC_OMR = 'aaaaaaaa-0000-0000-0000-000000000002'
  const LOC_ANN = 'bbbbbbbb-0000-0000-0000-000000000001'
  const now = new Date().toISOString()
  const pwHash = crypto.createHash('sha256').update(DEMO_PASSWORD).digest('hex')

  const OWNER_ID = 'user-owner-abc-0001-000000000001'
  const MGR_ID   = 'user-mgr-abc-0002-000000000002'
  const SALES_ID = 'user-sales-xyz-003-000000000003'
  // ABC sales floor — the assignable executives leads are routed to. Owner +
  // manager handle leads too in a small dealership, so the assignable team is
  // these five (matches the /assignments dashboard, which counts real leads).
  const RAVI_ID    = 'user-sales-abc-0004-000000000004'
  const KARTHIK_ID = 'user-sales-abc-0005-000000000005'
  const DIVYA_ID   = 'user-sales-abc-0006-000000000006'
  const ABC_TEAM   = [OWNER_ID, MGR_ID, RAVI_ID, KARTHIK_ID, DIVYA_ID]

  // Tenants
  await run(`INSERT INTO tenants VALUES (?,?,?,?,?,?)`, [ABC, 'ABC Nissan', 'Nissan', 'intelligence', 'active', JSON.stringify({ primary_color: '#C3002F', logo_url: null, theme: 'light' })])
  await run(`INSERT INTO tenants VALUES (?,?,?,?,?,?)`, [XYZ, 'XYZ Nissan', 'Nissan', 'growth', 'active', JSON.stringify({ primary_color: '#003366', logo_url: null, theme: 'light' })])

  // Locations
  await run(`INSERT INTO locations VALUES (?,?,?,?)`, [LOC_VEL, ABC, 'ABC Nissan — Velachery', 'active'])
  await run(`INSERT INTO locations VALUES (?,?,?,?)`, [LOC_OMR, ABC, 'ABC Nissan — OMR', 'active'])
  await run(`INSERT INTO locations VALUES (?,?,?,?)`, [LOC_ANN, XYZ, 'XYZ Nissan — Anna Nagar', 'active'])

  // Users
  await run(`INSERT INTO users VALUES (?,?,?,?,?,?,?)`, [OWNER_ID, ABC, 'owner@abcnissan.test', 'Arjun Krishnamurthy', 'dealer_owner', pwHash, now])
  await run(`INSERT INTO users VALUES (?,?,?,?,?,?,?)`, [MGR_ID,   ABC, 'manager@abcnissan.test', 'Priya Ramesh', 'dealer_manager', pwHash, now])
  await run(`INSERT INTO users VALUES (?,?,?,?,?,?,?)`, [SALES_ID, XYZ, 'sales@xyznissan.test', 'Rahul Mehta', 'sales_executive', pwHash, now])
  // Three more ABC sales executives so the assignable floor is five people.
  await run(`INSERT INTO users VALUES (?,?,?,?,?,?,?)`, [RAVI_ID,    ABC, 'ravi@abcnissan.test',    'Ravi Anand',     'sales_executive', pwHash, now])
  await run(`INSERT INTO users VALUES (?,?,?,?,?,?,?)`, [KARTHIK_ID, ABC, 'karthik@abcnissan.test', 'Karthik Raja',   'sales_executive', pwHash, now])
  await run(`INSERT INTO users VALUES (?,?,?,?,?,?,?)`, [DIVYA_ID,   ABC, 'divya@abcnissan.test',   'Divya Nair',     'sales_executive', pwHash, now])

  // Customers (ABC)
  const customers = [
    [uuidv4(), ABC, LOC_VEL, 'Ravi Kumar',     '+91-90000-00001', null,                  'Magnite', 'instagram'],
    [uuidv4(), ABC, LOC_OMR, 'Priya S',         '+91-90000-00002', 'priya.s@example.in',  'X-Trail', 'website'],
    [uuidv4(), ABC, LOC_VEL, 'Karthik Raja',    '+91-90000-00004', null,                  'Kicks',   'facebook'],
    [uuidv4(), ABC, LOC_VEL, 'Deepa Nair',      '+91-90000-00005', 'deepa.n@example.in',  'Magnite', 'walkin'],
    [uuidv4(), ABC, LOC_OMR, 'Suresh Babu',     '+91-90000-00006', null,                  'Terrano', 'oem'],
    [uuidv4(), ABC, LOC_OMR, 'Anjali Menon',    '+91-90000-00007', 'anjali.m@example.in', 'X-Trail', 'phone'],
    [uuidv4(), ABC, LOC_VEL, 'Vimal Chandran',  '+91-90000-00008', null,                  'Magnite', 'instagram'],
    [uuidv4(), ABC, LOC_OMR, 'Fatima Khan',     '+91-90000-00009', 'fatima.k@example.in', 'Kicks',   'website'],
    [uuidv4(), ABC, LOC_VEL, 'Gopal Iyer',      '+91-90000-00010', null,                  'Sunny',   'referral'],
    [uuidv4(), ABC, LOC_OMR, 'Lakshmi Rao',     '+91-90000-00011', 'lakshmi.r@example.in','X-Trail', 'event'],
  ]
  for (const c of customers) {
    const d = new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString()
    await run(`INSERT INTO customers (id,tenant_id,location_id,full_name,phone,email,preferred_vehicle,source_channel,created_at) VALUES (?,?,?,?,?,?,?,?,?)`, [...c, d])
  }

  // Leads
  const abcCusts = await all(`SELECT id FROM customers WHERE tenant_id=?`, [ABC])
  const stages  = ['new','contacted','qualified','test_drive','quotation','negotiation','won','lost']
  const scores  = ['hot','warm','cold']
  const sources = ['oem','website','facebook','instagram','walkin','phone','event','referral']
  const vehicles= ['Magnite','Kicks','X-Trail','Terrano','Sunny']
  const budgets = [800000,1200000,1500000,2000000,2500000,3200000,900000,1100000,1800000]

  const leadIds = []
  for (let i = 0; i < 15; i++) {
    const id = uuidv4()
    leadIds.push(id)
    const stage  = stages[i % stages.length]
    const score  = scores[i % scores.length]
    const cust   = abcCusts[i % abcCusts.length]
    const d = new Date(Date.now() - (i * 2 + 1) * 24 * 60 * 60 * 1000).toISOString()
    await run(`INSERT INTO leads (id,tenant_id,location_id,customer_id,source,stage,score,score_value,assigned_to,vehicle_interest,budget,notes,enquiry_count,created_at,updated_at,last_activity_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, [
      id, ABC, i % 2 === 0 ? LOC_VEL : LOC_OMR, cust.id,
      sources[i % sources.length], stage, score, Math.floor(Math.random() * 100),
      ABC_TEAM[i % ABC_TEAM.length],
      vehicles[i % vehicles.length], budgets[i % budgets.length],
      null, 1, d, d, d,
    ])
  }

  // Lead events — add test drives for first 3 leads
  for (const id of leadIds.slice(0, 3)) {
    await run(`INSERT INTO lead_events VALUES (?,?,?,?,?,?,?,?)`, [
      uuidv4(), ABC, id, 'test_drive', 'Test drive completed.', '{}', OWNER_ID, now,
    ])
  }

  // Notifications
  const notifs = [
    ['Hot lead follow-up needed', 'Ravi Kumar has had no contact for 48h — at risk of going cold.', 'unread'],
    ['Test drive scheduled', 'Priya S booked a test drive for tomorrow at OMR.', 'unread'],
    ['Lead won!', 'Karthik Raja purchased a Magnite. Great work!', 'read'],
    ['Campaign approved', 'Eid 2026 campaign post approved and scheduled for Instagram.', 'read'],
    ['2 new leads assigned', 'You have been assigned 2 new leads from Instagram.', 'unread'],
    ['Monthly target 80%', 'You are 80% toward your monthly target. Push for the close!', 'read'],
  ]
  for (const [title, message, status] of notifs) {
    await run(`INSERT INTO notifications VALUES (?,?,?,?,?,?)`, [uuidv4(), ABC, title, message, status, now])
  }

  // Audit logs
  const audits = [
    ['stage_change', 'lead', { to_stage: 'qualified' }],
    ['login', 'user', { email: 'owner@abcnissan.test' }],
    ['lead_assigned', 'lead', { assigned_to: 'Arjun Krishnamurthy' }],
    ['campaign_created', 'campaign', { name: 'Eid 2026 Campaign' }],
    ['stage_change', 'lead', { to_stage: 'test_drive' }],
    ['note_added', 'lead', { summary: 'Customer prefers red colour' }],
  ]
  for (const [action, entity_type, metadata] of audits) {
    await run(`INSERT INTO audit_logs VALUES (?,?,?,?,?,?,?)`, [uuidv4(), ABC, action, entity_type, null, JSON.stringify(metadata), now])
  }

  // Campaign
  const campId = uuidv4()
  await run(`INSERT INTO campaigns VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`, [
    campId, ABC, LOC_VEL, 'Eid 2026 Campaign', 'Festival', 'offer', 'active',
    JSON.stringify(['facebook', 'instagram']), '2026-06-01', '2026-06-30', 50000, now, now,
  ])

  const postStatuses = ['draft', 'scheduled', 'published', 'pending_approval', 'approved']
  for (let i = 0; i < 5; i++) {
    const status = postStatuses[i]
    await run(`INSERT INTO campaign_posts VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, [
      uuidv4(), ABC, campId,
      `Magnite Festive Offer — Post ${i + 1}`,
      `Great deals on Magnite this festive season! Limited period offer.`,
      'Book Now',
      JSON.stringify(['#NissanMagnite', '#Eid2026', '#Nissan']),
      i % 2 === 0 ? 'facebook' : 'instagram',
      status, 'approved', 'Magnite', '₹5000 cashback',
      null, null,
      status === 'scheduled' ? new Date(Date.now() + (i + 1) * 86400000).toISOString() : null,
      status === 'published' ? new Date(Date.now() - 86400000).toISOString() : null,
      now, now,
    ])
  }

  // Campaign insights
  await run(`INSERT INTO campaign_insights VALUES (?,?,?,?,?,?,?,?,?,?,?)`, [
    uuidv4(), campId, 12400, 28000, 1800, 34, 8, 22000, 647, 23.5,
    new Date(Date.now() - 86400000).toISOString(),
  ])

  // Market signals
  const signals = [
    [ABC, 'demand',      'SUV demand rising in Villupuram',       'Enquiries for compact SUVs are climbing week over week.', 'SUV enquiries', '+23% WoW', 'high',   'leads'],
    [ABC, 'opportunity', '5 hot leads pending follow-up',         'Five hot-scored leads have had no contact in over 48 hours.', 'Hot leads idle', '5 leads', 'high', 'leads'],
    [ABC, 'trend',       'Magnite is your lead engine',           'The Magnite accounts for 42% of leads.', 'Lead share', '42%', 'medium', 'leads'],
    [ABC, 'intent',      'Instagram shows strongest buying intent','Instagram-sourced leads progress to test drive faster.', 'Best channel', 'Instagram', 'medium', 'marketing'],
    [ABC, 'risk',        'Quotations going stale',                'Two quotations idle for 5+ days.', 'Idle quotations', '2', 'medium', 'leads'],
    [XYZ, 'demand',      'Kicks launch buzz building',            'Pre-launch interest in the Kicks is trending up.', 'Teaser reach', '21K', 'medium', 'marketing'],
  ]
  for (const [tid, kind, title, detail, ml, mv, sev, sm] of signals) {
    await run(`INSERT INTO market_signals VALUES (?,?,?,?,?,?,?,?,?,?,?)`, [uuidv4(), tid, kind, title, detail, ml, mv, sev, sm, 'open', now])
  }

  // Sales Executives (ABC Nissan)
  const abcExecutives = [
    [uuidv4(), ABC, 'Ravi',    'active', 0, 10],
    [uuidv4(), ABC, 'Priya',   'active', 0, 10],
    [uuidv4(), ABC, 'Karthik', 'active', 0, 10],
    [uuidv4(), ABC, 'Divya',   'active', 0, 10],
    [uuidv4(), ABC, 'Arjun',   'active', 0, 10],
  ]
  const abcExecIds = {}
  for (const [id, tenant, name, status, count, limit] of abcExecutives) {
    abcExecIds[name] = id
    await run(`INSERT INTO sales_executives VALUES (?,?,?,?,?,?)`, [id, tenant, name, status, count, limit])
  }

  // Sales Executives (XYZ Nissan)
  const xyzExecutives = [
    [uuidv4(), XYZ, 'Rahul',   'active', 0, 10],
    [uuidv4(), XYZ, 'Sneha',   'active', 0, 10],
  ]
  for (const [id, tenant, name, status, count, limit] of xyzExecutives) {
    await run(`INSERT INTO sales_executives VALUES (?,?,?,?,?,?)`, [id, tenant, name, status, count, limit])
  }

  console.log('✅ DuckDB seeded with demo data')
}

// ─── Lead Intake Logic ────────────────────────────────────────────────────────

// Fire-and-forget: automatically run the FastAPI Follow-up Agent (apps/api) for a
// freshly created lead — the same thing the Leads "Generate follow-up" button does,
// but triggered automatically on lead arrival. Non-blocking so intake stays fast;
// if the agent service is down it just logs a warning. Toggle with AUTO_FOLLOWUP=0.
const AGENT_API_URL = process.env.AGENT_API_URL || 'http://localhost:8000'
const AUTO_FOLLOWUP = process.env.AUTO_FOLLOWUP !== '0'

function triggerFollowupAgent(leadId) {
  if (!AUTO_FOLLOWUP || !leadId) return
  fetch(`${AGENT_API_URL}/followup/${leadId}`, { method: 'POST' })
    .then((r) => {
      if (r.ok) console.log(`🤝 auto follow-up done for lead ${leadId}`)
      else console.warn(`[auto-followup] agent returned ${r.status} for ${leadId}`)
    })
    .catch((e) => console.warn(`[auto-followup] agent unreachable (${AGENT_API_URL}): ${e.message}`))
}

// Dynamic Re-Scoring (Phase 6) — fire-and-forget, same pattern as triggerWorkflowAgent.
// Toggle with AUTO_RESCORE=0.
const AUTO_RESCORE = process.env.AUTO_RESCORE !== '0'

function triggerRescore(leadId, trigger = 'stage_change') {
  if (!AUTO_RESCORE || !leadId) return
  fetch(`${AGENT_API_URL}/rescore/${leadId}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ trigger }),
  })
    .then((r) => {
      if (r.ok) console.log(`📊 rescore done for lead ${leadId} (trigger=${trigger})`)
      else console.warn(`[rescore] agent returned ${r.status} for ${leadId}`)
    })
    .catch((e) => console.warn(`[rescore] agent unreachable: ${e.message}`))
}

// Same fire-and-forget shape as triggerFollowupAgent, for the Workflow Agent
// (Phase 3). The decision itself is made + persisted inside FastAPI; this
// shim only needs the response back so it can broadcast a `workflow_action`
// SSE event on ITS OWN sseClients — the one the browser's EventSource
// actually connects to in local dev (it points at VITE_SUPABASE_URL, i.e.
// this shim, not :8000 — same reasoning as the stage_change event in
// server.js's /events/stage-change). Toggle with AUTO_WORKFLOW=0.
const AUTO_WORKFLOW = process.env.AUTO_WORKFLOW !== '0'

function triggerWorkflowAgent(leadId, { customerName, vehicleInterest } = {}) {
  if (!AUTO_WORKFLOW || !leadId) return
  fetch(`${AGENT_API_URL}/workflow/${leadId}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ trigger_source: 'intake' }),
  })
    .then(async (r) => {
      if (!r.ok) {
        console.warn(`[auto-workflow] agent returned ${r.status} for ${leadId}`)
        return
      }
      const decision = await r.json()
      console.log(`🧭 auto workflow done for lead ${leadId}: ${(decision.actions || []).join(', ')}`)
      broadcastIntakeEvent({
        type: 'workflow_action',
        lead_id: leadId,
        classification: decision.classification,
        actions: decision.actions,
        escalated: decision.escalated,
        customer_name: customerName ?? null,
        vehicle_interest: vehicleInterest ?? null,
      })
    })
    .catch((e) => console.warn(`[auto-workflow] agent unreachable (${AGENT_API_URL}): ${e.message}`))
}

async function processIntakeLead(rawLead, source) {
  // Run the full pipeline: validate → normalize → score → assign.
  // validate.node.js calls the FastAPI lead_validator which persists customer+lead
  // and writes _lead_id / _customer_id back onto rawLead.
  const { normalized, scoring, assignment } = await intakeAgent.process(rawLead, source)
  const tenantId = ABC_TENANT_ID
  const now = new Date().toISOString()

  // Pipeline outputs (with safe fallbacks while teammate agents are stubs).
  const score      = scoring?.score ?? 'warm'
  const scoreValue = scoring?.score_value ?? 50
  const assignedTo = assignment?.assigned_to ?? null
  // Agent attribution: how was this lead scored? The Python agent reports
  // "groq_holistic" / "deterministic" in scoring.detail; the JS fallback has no
  // detail, so we tag it "static_js". This lets the UI show which agent ran.
  const scoredBy = scoring?.detail?.scored_by ?? (scoring ? 'static_js' : null)
  const scoreReasons = JSON.stringify(scoring?.reasons ?? [])
  // Optional human-facing notice from the scoring agent (e.g. fallback warning); null = normal.
  const scoreNotice = scoring?.score_notice ?? scoring?.detail?.score_notice ?? null

  // Intake preferences captured from the source form / demo.
  const testDrive    = normalized.test_drive_required ? true : false
  const budget       = normalized.budget ?? null
  const buyTimeline  = normalized.buy_timeline_days ?? null
  const callbackDays = normalized.callback_days ?? null
  const contactMedium = normalized.contact_medium ?? null
  // Enquiry-form signal fields (persisted so the lead detail can show them back).
  const financing = normalized.financing ?? null
  const nissanRelationship = normalized.nissan_relationship ?? null
  const brandConsideration = normalized.brand_consideration ?? null
  const comparingBrands = normalized.comparing_brands ?? null
  const purchaseReason = normalized.purchase_reason ?? null

  let leadId     = rawLead._lead_id     ?? null
  let customerId = rawLead._customer_id ?? null

  if (leadId && rawLead._is_duplicate) {
    // Validation Agent (Phase 1): a repeat enquiry only gets enquiry_count
    // incremented + a lead_interactions record — both already done by
    // lead_validator's dedup_and_persist. This submission's freshly computed
    // score/assignment are NOT written over the existing lead's row (still
    // surfaced in the API response/broadcast below for visibility).
  } else if (leadId) {
    // FastAPI validator already inserted customer + lead — patch with pipeline outputs.
    await run(
      `UPDATE leads SET score=?, score_value=?, assigned_to=?,
        vehicle_interest=?, budget=?, test_drive_required=?,
        purchase_timeline_days=?, callback_within_days=?, contact_medium=?,
        financing=?, nissan_relationship=?, brand_consideration=?, comparing_brands=?, purchase_reason=?,
        scored_by=?, score_reasons=?, score_notice=?,
        updated_at=?, last_activity_at=?
       WHERE id=?`,
      [score, scoreValue, assignedTo,
       normalized.vehicle, budget, testDrive,
       buyTimeline, callbackDays, contactMedium,
       financing, nissanRelationship, brandConsideration, comparingBrands, purchaseReason,
       scoredBy, scoreReasons, scoreNotice,
       now, now,
       leadId],
    )
  } else {
    // Fallback: FastAPI was unreachable — insert directly.
    customerId = uuidv4()
    leadId     = uuidv4()
    await run(
      `INSERT INTO customers (id,tenant_id,location_id,full_name,phone,email,preferred_vehicle,source_channel,created_at) VALUES (?,?,?,?,?,?,?,?,?)`,
      [customerId, tenantId, LOC_VEL_ID, normalized.name, normalized.phone, normalized.email || null, normalized.vehicle, source, now]
    )
    await run(
      `INSERT INTO leads (id,tenant_id,location_id,customer_id,source,stage,score,score_value,assigned_to,vehicle_interest,budget,notes,test_drive_required,purchase_timeline_days,callback_within_days,contact_medium,financing,nissan_relationship,brand_consideration,comparing_brands,purchase_reason,scored_by,score_reasons,score_notice,created_at,updated_at,last_activity_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
      [leadId, tenantId, LOC_VEL_ID, customerId, source, 'new', score, scoreValue, assignedTo, normalized.vehicle, budget, null, testDrive, buyTimeline, callbackDays, contactMedium, financing, nissanRelationship, brandConsideration, comparingBrands, purchaseReason, scoredBy, scoreReasons, scoreNotice, now, now, now]
    )
  }

  // ── Agent attribution timeline ──────────────────────────────────────────────
  // Record what each pipeline agent did, in order, so the lead detail page can
  // show exactly which agent produced which value (validate→normalize→score→assign).
  const scoredByLabel = scoredBy === 'claude_holistic' ? 'Claude' : scoredBy === 'groq_holistic' ? 'Groq LLM' : scoredBy === 'deterministic' ? 'agent heuristic' : 'static fallback'
  const agentEvents = [
    { agent: 'Validate Agent · Amirtha',  stage: 1, summary: `Validated lead — name & phone present, accepted into pipeline.` },
    { agent: 'Normalize Agent · Partha',  stage: 2, summary: `Normalized fields — ${normalized.vehicle ?? 'no vehicle'}, ${budget ? '₹' + Math.round(budget / 100000) + 'L' : 'no budget'}, ${testDrive ? 'test drive' : 'no test drive'}.` },
    { agent: 'Scoring Agent · Csriram',   stage: 3, summary: `Scored ${String(score).toUpperCase()} (${scoreValue}/100) via ${scoredByLabel}.` },
    { agent: 'Assignment Agent · Keerthana', stage: 4, summary: assignment?.assignee_name ? `Assigned to ${assignment.assignee_name} (least-loaded executive).` : `No executive available to assign.` },
  ]
  const nowMs = Date.parse(now)
  for (const ev of agentEvents) {
    // Stagger by stage so the pipeline reads validate→normalize→score→assign in order.
    const ts = new Date(nowMs + ev.stage * 1000).toISOString()
    await run(
      `INSERT INTO lead_events (id,tenant_id,lead_id,type,summary,metadata,created_by,created_at) VALUES (?,?,?,?,?,?,?,?)`,
      [uuidv4(), tenantId, leadId, 'agent', ev.summary, JSON.stringify({ agent: ev.agent, stage: ev.stage }), null, ts]
    )
  }

  const assignNote = assignment?.assignee_name ? ` · assigned to ${assignment.assignee_name}` : ''
  await run(
    `INSERT INTO notifications (id,tenant_id,title,message,status,created_at) VALUES (?,?,?,?,?,?)`,
    [
      uuidv4(),
      tenantId,
      `New ${source} lead (${score})`,
      `${normalized.name} enquired about ${normalized.vehicle ?? 'a vehicle'}${normalized.city ? ' from ' + normalized.city : ''}${assignNote}.`,
      'unread',
      now,
    ]
  )

  const lead = {
    id: leadId,
    customer_name: normalized.name,
    source,
    stage: 'new',
    score,
    score_value: scoreValue,
    assigned_to: assignedTo,
    assignee_name: assignment?.assignee_name ?? null,
    vehicle_interest: normalized.vehicle,
    city: normalized.city,
    budget,
    test_drive_required: testDrive,
    purchase_timeline_days: buyTimeline,
    callback_within_days: callbackDays,
    contact_medium: contactMedium,
    financing,
    nissan_relationship: nissanRelationship,
    brand_consideration: brandConsideration,
    comparing_brands: comparingBrands,
    purchase_reason: purchaseReason,
    scored_by: scoredBy,
    score_notice: scoreNotice,
    created_at: now,
  }
  broadcastIntakeEvent({ type: 'new_lead', lead, source })
  // Auto-run the follow-up agent for the new lead (non-blocking).
  triggerFollowupAgent(leadId)
  // Auto-run the Workflow Agent (Phase 3) — decides next action(s), persists
  // a workflow_actions/lead_tasks/lead_events record, escalates if hot.
  triggerWorkflowAgent(leadId, { customerName: normalized.name, vehicleInterest: normalized.vehicle })
  pushLog({
    type: 'success',
    source,
    lead_id: leadId,
    customer_name: normalized.name,
    phone: normalized.phone,
    vehicle: normalized.vehicle,
    score,
    is_duplicate: !!rawLead._is_duplicate,
  })
  return { success: true, lead, scoring, assignment }
}

function startDemoGenerators() {
  const fbLeads = [
    { name: 'Ramesh Kumar',      phone: '+919876543211', email: 'ramesh.kumar@gmail.com',      vehicle: 'Nissan Magnite', city: 'Chennai',    test_drive: true,  budget: 1000000, buy_timeline_days: 30,  callback_days: 2,  contact_medium: 'WhatsApp' },
    { name: 'Pavithra Sundaram', phone: '+919765432109', email: 'pavithra.s@yahoo.com',        vehicle: 'Nissan Kicks',   city: 'Coimbatore', test_drive: false, budget: 1500000, buy_timeline_days: 90,  callback_days: 7,  contact_medium: 'Phone call' },
    { name: 'Senthil Nathan',    phone: '+919654321098', email: 'senthil.nathan@outlook.com',  vehicle: 'Nissan Magnite', city: 'Madurai',    test_drive: true,  budget: 700000,  buy_timeline_days: 7,   callback_days: 1,  contact_medium: 'WhatsApp' },
    { name: 'Nithya Balaji',     phone: '+919543210987', email: 'nithya.balaji@gmail.com',     vehicle: 'Nissan X-Trail', city: 'Salem',      test_drive: true,  budget: 2100000, buy_timeline_days: 30,  callback_days: 2,  contact_medium: 'Phone call' },
    { name: 'Murugan Pillai',    phone: '+919432109876', email: 'murugan.pillai@rediffmail.com',vehicle: 'Nissan Terrano', city: 'Trichy',    test_drive: false, budget: 1500000, buy_timeline_days: 180, callback_days: 14, contact_medium: 'Email' },
  ]
  const igLeads = [
    { name: 'Keerthana Raj',    phone: '+919321098765', email: 'keerthana.raj@gmail.com',     vehicle: 'Nissan Magnite', city: 'Chennai',   test_drive: true,  budget: 1000000, buy_timeline_days: 7,   callback_days: 1,  contact_medium: 'WhatsApp' },
    { name: 'Aravind Selvam',   phone: '+919210987654', email: 'aravind.selvam@gmail.com',    vehicle: 'Nissan Kicks',   city: 'Bangalore', test_drive: false, budget: 1500000, buy_timeline_days: 90,  callback_days: 7,  contact_medium: 'SMS' },
    { name: 'Shalini Devi',     phone: '+919109876543', email: 'shalini.devi@yahoo.com',      vehicle: 'Nissan Magnite', city: 'Hyderabad', test_drive: true,  budget: 700000,  buy_timeline_days: 30,  callback_days: 2,  contact_medium: 'WhatsApp' },
    { name: 'Prashanth Kumar',  phone: '+919098765432', email: 'prashanth.k@outlook.com',     vehicle: 'Nissan X-Trail', city: 'Pune',      test_drive: true,  budget: 2800000, buy_timeline_days: 7,   callback_days: 1,  contact_medium: 'Phone call' },
    { name: 'Anitha Nair',      phone: '+918987654321', email: 'anitha.nair@gmail.com',       vehicle: 'Nissan Kicks',   city: 'Kochi',     test_drive: false, budget: 1000000, buy_timeline_days: 180, callback_days: 14, contact_medium: 'Email' },
  ]
  let fbIdx = 0
  let igIdx = 0

  setInterval(() => {
    const lead = fbLeads[fbIdx % fbLeads.length]
    fbIdx++
    processIntakeLead(lead, 'facebook').catch(e => console.error('[Demo FB]', e.message))
    console.log(`\n📘 [Demo] Facebook lead: ${lead.name}`)
  }, 30000)

  // Instagram starts 15 s after Facebook to stagger arrivals
  setTimeout(() => {
    setInterval(() => {
      const lead = igLeads[igIdx % igLeads.length]
      igIdx++
      processIntakeLead(lead, 'instagram').catch(e => console.error('[Demo IG]', e.message))
      console.log(`\n📸 [Demo] Instagram lead: ${lead.name}`)
    }, 30000)
  }, 15000)

  console.log('🤖 Demo generators started — Facebook every 30 s, Instagram every 30 s (offset 15 s)')
}

// ─── Express ──────────────────────────────────────────────────────────────────

const app = express()
app.use(cors({ origin: true, credentials: true }))
// 20 MB limit so WhatsApp media uploads (base64-encoded image/video/pdf) fit.
app.use(express.json({ limit: '20mb' }))
app.use((req, res, next) => {
  console.log(`${req.method} ${req.url}`)
  next()
})

// ── WhatsApp media upload (local dev only) ────────────────────────────────────
// The WhatsApp send card lets reps pick a file from their device. The browser
// reads it as base64 and POSTs it here. We write it to uploads/ on disk and
// return a localhost URL that the mock WhatsApp provider "sends" (it doesn't
// actually call Meta in dev, so localhost URLs are fine).
const UPLOADS_DIR = path.join(__dirname, 'uploads')
if (!fs.existsSync(UPLOADS_DIR)) fs.mkdirSync(UPLOADS_DIR, { recursive: true })
app.use('/uploads', express.static(UPLOADS_DIR))

app.post('/upload', (req, res) => {
  const { filename, data } = req.body ?? {}
  if (!filename || !data) return res.status(400).json({ error: 'filename and data are required' })
  // Sanitise: only allow safe characters to avoid path traversal.
  const safe = filename.replace(/[^a-zA-Z0-9._-]/g, '_')
  const name = `${Date.now()}_${safe}`
  const dest = path.join(UPLOADS_DIR, name)
  try {
    fs.writeFileSync(dest, Buffer.from(data, 'base64'))
    const host = req.get('host') || 'localhost:54321'
    res.json({ url: `http://${host}/uploads/${name}`, filename: name })
  } catch (err) {
    res.status(500).json({ error: String(err) })
  }
})

// ─── Auth routes ──────────────────────────────────────────────────────────────

// Sign in
app.post('/auth/v1/token', async (req, res) => {
  if (req.query.grant_type !== 'password') return res.status(400).json({ error: 'unsupported grant_type' })
  const { email, password } = req.body || {}
  if (!email || !password) return res.status(400).json({ error: 'email and password required' })

  const hash = crypto.createHash('sha256').update(password).digest('hex')
  const rows = await all(`SELECT * FROM users WHERE email=? AND password_hash=?`, [email, hash])
  const user = rows[0]
  if (!user) return res.status(400).json({ error: 'Invalid login credentials', error_code: 'invalid_credentials' })

  const accessToken = jwt.sign(
    { sub: user.id, email: user.email, role: 'authenticated', tenant_id: user.tenant_id, iss: 'supabase', aud: 'authenticated' },
    JWT_SECRET, { expiresIn: '7d' }
  )
  res.json({
    access_token: accessToken,
    token_type: 'bearer',
    expires_in: 604800,
    expires_at: Math.floor(Date.now() / 1000) + 604800,
    refresh_token: uuidv4(),
    user: {
      id: user.id, email: user.email, role: 'authenticated',
      app_metadata: { tenant_id: user.tenant_id },
      user_metadata: { full_name: user.full_name },
      created_at: user.created_at,
    },
  })
})

// Refresh token (just re-issue)
app.post('/auth/v1/token', async (req, res) => {
  res.status(400).json({ error: 'refresh not supported in local mode — sign in again' })
})

// Get user
app.get('/auth/v1/user', async (req, res) => {
  const auth = req.headers.authorization || ''
  if (!auth.startsWith('Bearer ')) return res.status(401).json({ error: 'Not authenticated' })
  try {
    const decoded = jwt.verify(auth.slice(7), JWT_SECRET)
    const rows = await all(`SELECT * FROM users WHERE id=?`, [decoded.sub])
    const user = rows[0]
    if (!user) return res.status(401).json({ error: 'User not found' })
    res.json({
      id: user.id, email: user.email, role: 'authenticated',
      app_metadata: { tenant_id: user.tenant_id },
      user_metadata: { full_name: user.full_name },
      created_at: user.created_at,
    })
  } catch { res.status(401).json({ error: 'Invalid token' }) }
})

// Sign out
app.post('/auth/v1/logout', (req, res) => res.json({ message: 'Logged out' }))

// ─── Lead Intake API ─────────────────────────────────────────────────────────

// SSE stream — frontend connects here to receive realtime lead notifications
app.get('/intake/stream', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream')
  res.setHeader('Cache-Control', 'no-cache')
  res.setHeader('Connection', 'keep-alive')
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.flushHeaders()
  const clientId = ++sseCounter
  sseClients.set(clientId, res)
  res.write(`data: ${JSON.stringify({ type: 'connected' })}\n\n`)
  req.on('close', () => sseClients.delete(clientId))
})

// All sources (website / facebook / instagram) POST here; the LangChain agent normalizes the lead
app.post('/intake/leads', async (req, res) => {
  const { source = 'website', ...rawLead } = req.body ?? {}
  try {
    const result = await processIntakeLead(rawLead, source)
    res.json(result)
  } catch (err) {
    console.error('[POST /intake/leads]', err.message)
    pushLog({
      type: 'failure',
      source,
      name: rawLead.name ?? rawLead.full_name ?? null,
      phone: rawLead.phone ?? null,
      errors: [err.message],
    })
    res.status(400).json({ error: err.message })
  }
})

app.get('/intake/logs', (_req, res) => res.json(intakeLogs))

// Lead Board UI (Phase 2) — broadcast a stage move so every connected
// dashboard/board tab stays in sync. updateLeadStage() (apps/web) writes the
// DB row itself via the usual PostgREST route, then best-effort POSTs here;
// a broadcast failure must never fail the underlying stage-change mutation.
app.post('/events/stage-change', (req, res) => {
  const { lead_id, from_stage, to_stage, customer_name, vehicle_interest } = req.body ?? {}
  broadcastIntakeEvent({
    type: 'stage_change',
    lead_id, from_stage, to_stage, customer_name, vehicle_interest,
    changed_at: new Date().toISOString(),
  })
  // Phase 6: re-score on every stage change (fire-and-forget).
  triggerRescore(lead_id, 'stage_change')
  res.status(204).end()
})

// WhatsApp Agent (Phase 4) — FastAPI's webhook handler calls this after
// persisting a delivery-status update so the browser's EventSource (which
// connects to this shim, not to :8000) gets the real-time status badge
// update. Same pattern as /events/stage-change above.
app.post('/events/whatsapp-status', (req, res) => {
  const { lead_id, wamid, status, updated_at } = req.body ?? {}
  broadcastIntakeEvent({
    type: 'whatsapp_status',
    lead_id, wamid, status,
    updated_at: updated_at ?? new Date().toISOString(),
  })
  res.status(204).end()
})

// Dynamic Re-Scoring (Phase 6) — FastAPI's rescore_lead() calls this after
// completing a re-score so the browser's score badge and history panel update live.
app.post('/events/rescore-complete', (req, res) => {
  const { lead_id, new_score, previous_score, score_changed, trigger } = req.body ?? {}
  broadcastIntakeEvent({
    type: 'rescore_complete',
    lead_id, new_score, previous_score, score_changed, trigger,
    updated_at: new Date().toISOString(),
  })
  res.status(204).end()
})

// WhatsApp Agent (Phase 4) — FastAPI broadcasts inbound customer replies so the
// browser receives a real-time notification and the messages panel auto-reloads.
app.post('/events/whatsapp-inbound', (req, res) => {
  const { lead_id, customer_name, body_preview } = req.body ?? {}
  broadcastIntakeEvent({
    type: 'whatsapp_inbound',
    lead_id, customer_name, body_preview,
    received_at: new Date().toISOString(),
  })
  res.status(204).end()
})

// ─── PostgREST-compatible REST routes ─────────────────────────────────────────

// Parse `col=eq.value`, `col=not.is.null` etc from query string
function parseFilters(query, skipKeys = []) {
  const skip = new Set(['select', 'order', 'limit', 'offset', 'head', ...skipKeys])
  const filters = []
  const params = []

  for (const [key, val] of Object.entries(query)) {
    if (skip.has(key)) continue
    const str = String(val)

    // not.is.null
    if (str === 'not.is.null') { filters.push(`${key} IS NOT NULL`); continue }
    if (str === 'is.null')     { filters.push(`${key} IS NULL`);     continue }

    const m = str.match(/^(eq|neq|gt|lt|gte|lte|like|ilike)\.(.*)$/)
    if (!m) continue
    const [, op, v] = m
    const sqlOp = { eq: '=', neq: '!=', gt: '>', lt: '<', gte: '>=', lte: '<=', like: 'LIKE', ilike: 'ILIKE' }[op]
    filters.push(`${key} ${sqlOp} ?`)
    params.push(v)
  }
  return { filters, params }
}

function buildWhere(filters) {
  return filters.length ? `WHERE ${filters.join(' AND ')}` : ''
}

function buildOrder(orderParam) {
  if (!orderParam) return ''
  const parts = String(orderParam).split(',').map(o => {
    const [col, dir] = o.trim().split('.')
    return `${col} ${dir?.toUpperCase() === 'DESC' ? 'DESC' : 'ASC'}`
  })
  return `ORDER BY ${parts.join(', ')}`
}

// Detect join selects like: customer:customers!leads_customer_id_fkey(full_name)
const JOIN_RE = /(\w+):(\w+)![\w_]*\(([^)]+)\)/g

function parseSelect(selectRaw, table) {
  const joins = []
  let clean = selectRaw

  for (const m of selectRaw.matchAll(new RegExp(JOIN_RE.source, 'g'))) {
    const [full, alias, joinTable, cols] = m
    joins.push({ alias, joinTable, cols: cols.split(',').map(c => c.trim()) })
    clean = clean.replace(full, '')
  }
  // Also handle simpler: campaign:campaigns(name)
  const SIMPLE_JOIN_RE = /(\w+):(\w+)\(([^)]+)\)/g
  for (const m of clean.matchAll(new RegExp(SIMPLE_JOIN_RE.source, 'g'))) {
    const [full, alias, joinTable, cols] = m
    joins.push({ alias, joinTable, cols: cols.split(',').map(c => c.trim()) })
    clean = clean.replace(full, '')
  }

  // Clean up leftover commas
  clean = clean.split(',').map(c => c.trim()).filter(Boolean).join(', ') || '*'

  return { baseCols: clean, joins }
}

// Build the SQL for joins
function buildJoinSql(table, baseCols, joins, where, order, limit, offset) {
  const joinClauses = []
  const extraSelects = []
  const fkMap = {
    // leads → customers via customer_id
    customers: { fk: `${table}.customer_id`, pk: 'customers.id' },
    // leads → users via assigned_to
    users:     { fk: `${table}.assigned_to`,  pk: 'users.id' },
    // campaign_posts → campaigns via campaign_id
    campaigns: { fk: `${table}.campaign_id`,  pk: 'campaigns.id' },
  }
  for (const { alias, joinTable, cols } of joins) {
    const fk = fkMap[joinTable]
    if (!fk) continue
    const safeAlias = `j_${alias}`
    joinClauses.push(`LEFT JOIN ${joinTable} AS ${safeAlias} ON ${fk.fk} = ${safeAlias}.${fk.pk.split('.')[1]}`)
    for (const col of cols) {
      extraSelects.push(`${safeAlias}.${col} AS __${alias}__${col}`)
    }
  }

  const selectPart = [
    baseCols === '*' ? `${table}.*` : baseCols.split(',').map(c => `${table}.${c.trim()}`).join(', '),
    ...extraSelects,
  ].join(', ')

  // When joining, unqualified column refs in WHERE are ambiguous (e.g. "id" exists in
  // leads, customers, and users). Prefix every bare column name in the WHERE clause
  // with the main table so DuckDB can resolve them without error.
  let qualifiedWhere = where
  if (joinClauses.length > 0 && where) {
    // Replace patterns like "WHERE colname OP" and "AND colname OP"
    // where colname has no dot (unqualified).
    qualifiedWhere = where.replace(
      /(WHERE|AND|OR)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*(=|!=|<>|>=|<=|>|<|IS\s+NOT\s+NULL|IS\s+NULL|LIKE|ILIKE)/gi,
      (m, kw, col, op) => `${kw} ${table}.${col} ${op}`
    )
  }

  const sql = `SELECT ${selectPart} FROM ${table} ${joinClauses.join(' ')} ${qualifiedWhere} ${order} ${limit} ${offset}`
  return { sql, joins }
}

// Reshape rows: pull __alias__col fields into nested objects
function reshapeJoinRows(rows, joins) {
  return rows.map(row => {
    const out = {}
    const nested = {}

    for (const { alias, cols } of joins) {
      nested[alias] = {}
      for (const col of cols) {
        const key = `__${alias}__${col}`
        nested[alias][col] = row[key] ?? null
        // Don't include in flat row
      }
    }

    for (const [k, v] of Object.entries(row)) {
      if (k.startsWith('__')) continue
      out[k] = parseJson(v)
    }

    for (const [alias, obj] of Object.entries(nested)) {
      // If all values are null, the join had no match
      const hasData = Object.values(obj).some(v => v !== null)
      out[alias] = hasData ? obj : null
    }

    return out
  })
}

app.all('/rest/v1/:table', async (req, res) => {
  const { table } = req.params
  const method = req.method
  const q = req.query
  const prefer = String(req.headers['prefer'] || '')
  const accept = String(req.headers['accept'] || '')
  const wantsCount = prefer.includes('count=exact')
  const headOnly = q.head === 'true'
  // .single() / .maybeSingle() send this Accept header and expect ONE object, not an array.
  const singleObject = accept.includes('application/vnd.pgrst.object+json')

  const selectRaw = String(q.select || '*')
  const { filters, params: filterParams } = parseFilters(q)
  const where = buildWhere(filters)
  const order = buildOrder(q.order)
  const limitClause  = q.limit  ? `LIMIT ${parseInt(q.limit)}`   : ''
  const offsetClause = q.offset ? `OFFSET ${parseInt(q.offset)}` : ''

  try {
    // ── GET / HEAD ──
    // supabase-js sends HTTP HEAD (not GET+head=true) for .select('*',{count:'exact',head:true})
    if (method === 'GET' || method === 'HEAD') {
      let count = 0
      if (wantsCount || headOnly || method === 'HEAD') {
        const rows = await all(`SELECT COUNT(*) AS cnt FROM ${table} ${where}`, filterParams)
        count = Number(rows[0]?.cnt ?? 0)
        res.setHeader('Content-Range', `0-${Math.max(count - 1, 0)}/${count}`)
        res.setHeader('Range-Unit', 'items')
        if (headOnly || method === 'HEAD') return res.status(200).end()
      }

      const { baseCols, joins } = parseSelect(selectRaw, table)

      let rows
      if (joins.length > 0) {
        const { sql } = buildJoinSql(table, baseCols, joins, where, order, limitClause, offsetClause)
        const raw = await all(sql, filterParams)
        rows = reshapeJoinRows(raw, joins)
      } else {
        const cols = baseCols === '*' ? '*' : baseCols
        rows = (await all(`SELECT ${cols} FROM ${table} ${where} ${order} ${limitClause} ${offsetClause}`, filterParams))
          .map(transformRow)
      }

      if (!wantsCount) {
        res.setHeader('Content-Range', `0-${Math.max(rows.length - 1, 0)}/${rows.length}`)
      }
      // .single()/.maybeSingle() expect a single object (or null), not an array.
      if (singleObject) return res.json(rows[0] ?? null)
      return res.json(rows)
    }

    // ── POST (insert) ──
    if (method === 'POST') {
      const body = Array.isArray(req.body) ? req.body : [req.body]
      const inserted = []
      for (const row of body) {
        if (!row.id) row.id = uuidv4()
        if (!row.created_at) row.created_at = new Date().toISOString()
        const cols = Object.keys(row).join(', ')
        const ph   = Object.keys(row).map(() => '?').join(', ')
        await run(`INSERT INTO ${table} (${cols}) VALUES (${ph})`, Object.values(stringifyRow(row)))
        inserted.push(row)
      }
      if (singleObject) return res.status(201).json(inserted[0] ?? null)
      return res.status(201).json(inserted)
    }

    // ── PATCH (update) ──
    if (method === 'PATCH') {
      if (!req.body || Object.keys(req.body).length === 0) return res.status(204).send()
      const sets = Object.keys(req.body).map(k => `${k} = ?`).join(', ')
      await run(`UPDATE ${table} SET ${sets} ${where}`, [...Object.values(stringifyRow(req.body)), ...filterParams])
      return res.status(204).send()
    }

    // ── DELETE ──
    if (method === 'DELETE') {
      await run(`DELETE FROM ${table} ${where}`, filterParams)
      return res.status(204).send()
    }

    res.status(405).json({ error: 'Method not allowed' })
  } catch (err) {
    console.error(`[${method} /rest/v1/${table}]`, err.message)
    res.status(500).json({ message: err.message, hint: err.message })
  }
})

// ─── Helper: Extract tenant from JWT ──────────────────────────────────────────
function getTenantFromAuth(req) {
  const auth = req.headers.authorization || ''
  if (!auth.startsWith('Bearer ')) return null
  try {
    const decoded = jwt.verify(auth.slice(7), JWT_SECRET)
    return decoded.tenant_id
  } catch {
    return null
  }
}

// ─── Assignment Agent routes ──────────────────────────────────────────────────

// POST /api/assign-lead — Assign a scored lead to an executive (using LangGraph)
app.post('/api/assign-lead', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const { lead_id, score } = req.body
    if (!lead_id || !score) {
      return res.status(400).json({ error: 'lead_id and score required' })
    }
    const result = await assignmentAgentGraph.assignLeadWithGraph(tenantId, { lead_id, score })
    return res.json(result)
  } catch (err) {
    console.error('POST /api/assign-lead error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// POST /api/complete-lead — Mark a lead as completed
app.post('/api/complete-lead', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const { lead_id, executive_id } = req.body
    if (!lead_id || !executive_id) {
      return res.status(400).json({ error: 'lead_id and executive_id required' })
    }
    const result = await assignmentAgent.completeLead(tenantId, lead_id, executive_id)
    return res.json(result)
  } catch (err) {
    console.error('POST /api/complete-lead error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// POST /api/deactivate-executive — Deactivate an executive and reassign their leads
app.post('/api/deactivate-executive', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const { executive_id } = req.body
    if (!executive_id) {
      return res.status(400).json({ error: 'executive_id required' })
    }
    const result = await assignmentAgent.deactivateExecutive(tenantId, executive_id)
    return res.json(result)
  } catch (err) {
    console.error('POST /api/deactivate-executive error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// GET /api/executives — Get all executives with their current load
app.get('/api/executives', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const executives = await assignmentAgent.getExecutives(tenantId)
    return res.json(executives)
  } catch (err) {
    console.error('GET /api/executives error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// GET /api/assignment-history — Get full assignment history
app.get('/api/assignment-history', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const limit = parseInt(req.query.limit) || 50
    const history = await assignmentAgent.getAssignmentHistory(tenantId, limit)
    return res.json(history)
  } catch (err) {
    console.error('GET /api/assignment-history error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// GET /api/executives/:id/queue — Get prioritized lead queue for an executive
app.get('/api/executives/:id/queue', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const executiveId = req.params.id
    const priorityMap = { 'hot': 3, 'warm': 2, 'cold': 1 }

    const reader = await conn.runAndReadAll(
      interpolate(
        `SELECT assignment_id, lead_id, score, priority_rank, assigned_at
         FROM lead_assignments
         WHERE tenant_id = ? AND executive_id = ?
         ORDER BY priority_rank DESC, assigned_at ASC`,
        [tenantId, executiveId]
      )
    )
    const queue = reader.getRowObjectsJson()

    const enriched = queue.map((item, idx) => ({
      ...item,
      position: idx + 1,
      priority_label: Object.keys(priorityMap).find(k => priorityMap[k] === item.priority_rank) || 'unknown'
    }))

    return res.json(enriched)
  } catch (err) {
    console.error('GET /api/executives/:id/queue error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// GET /api/notifications — Get notifications for the tenant
app.get('/api/notifications', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const unreadOnly = req.query.unread === 'true'
    const limit = parseInt(req.query.limit) || 20
    const notifications = await assignmentAgent.getNotifications(tenantId, unreadOnly, limit)
    return res.json(notifications)
  } catch (err) {
    console.error('GET /api/notifications error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// POST /api/notifications/:id/read — Mark notification as read
app.post('/api/notifications/:id/read', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const result = await assignmentAgent.markNotificationRead(req.params.id)
    return res.json(result)
  } catch (err) {
    console.error('POST /api/notifications/:id/read error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// GET /api/dashboard/stats — Get assignment dashboard stats
app.get('/api/dashboard/stats', async (req, res) => {
  try {
    const tenantId = getTenantFromAuth(req)
    if (!tenantId) return res.status(401).json({ error: 'Unauthorized' })

    const stats = await assignmentAgent.getDashboardStats(tenantId)
    return res.json(stats)
  } catch (err) {
    console.error('GET /api/dashboard/stats error:', err.message)
    res.status(500).json({ error: err.message })
  }
})

// ─── Boot ─────────────────────────────────────────────────────────────────────

async function main() {
  ensureWebEnv()
  console.log('🦆 Initializing DuckDB...')
  await initDuckDB()
  assignmentAgent.setDb(conn)
  assignmentAgentGraph.setDb(conn)
  await initSchema()
  await seed()
  intakeAgent = new LeadIntakeAgent({ all, run, tenantId: ABC_TENANT_ID })
  // Demo Facebook/Instagram lead generators are OFF by default. Set DEMO_LEADS=1
  // to re-enable the simulated drip of incoming leads.
  if (process.env.DEMO_LEADS === '1') startDemoGenerators()
  app.listen(PORT, () => {
    console.log(`\n🚀 Local Supabase API running on http://localhost:${PORT}`)
    console.log(`\nDemo accounts (password: ${DEMO_PASSWORD}):`)
    console.log('  owner@abcnissan.test   — dealer_owner (ABC Nissan)')
    console.log('  manager@abcnissan.test — dealer_manager (ABC Nissan)')
    console.log('  sales@xyznissan.test   — sales_executive (XYZ Nissan)')
    console.log('\nFrontend: http://localhost:3000')
    console.log('\n📥 Intake:  POST http://localhost:54321/intake/leads')
    console.log('📡 Stream:  GET  http://localhost:54321/intake/stream')
    console.log('🌐 Form:    http://localhost:3000/book-test-drive')
  })
}

main().catch(err => { console.error('Fatal:', err); process.exit(1) })
